### ISSUE TITLE
UserAgentParser cann't parse the "MOBILE ANDROID 3.1.1" exactly,int fact,deviceType:mobile,platform:android,and version 3.1.1

### ISSUE THREAD

**Issue by weiyongyuan** [blueconic/browscap-java#11]
browser=Default Browser
browserType=Default Browser
browserMajorVersion=Unknown
deviceType=Unknown
platform=Unknown
platformVersion=Unknown
fake=Unknown
IS_CRAWLER=Unknown

**Comment by paulrutter** [comment]
@weiyongyuan can you make this issue a bit more explicit? 
- What is the exact user agent that is not parsed correctly? 
- This module follows http://browscap.org/ua-lookup, does it work correctly there? If not, you should file an issue here: https://github.com/browscap/browscap/issues.

Let me know, thanks.

**Comment by paulrutter** [comment]
I see you filed an issue(https://github.com/browscap/browscap/issues/1837)  so closing this one.
