### ISSUE TITLE
Valid values for device type

### ISSUE THREAD

**Issue by moranges** [blueconic/browscap-java#12]
Hi,

We have integrated with this library and it is working fine for us! Thank you!

Now, we see Mobile Phone, Desktop, Tablet, Console, TV Device as examples listed for device type. Is there any place where we can see all the possible values and what devices in the real world they belong to?

Thanks in advance,

Mariano.

**Comment by paulrutter** [comment]
Thanks, glad to hear it's working for you.
The list of possible values can be found ujd here: https://github.com/browscap/browscap/wiki/Resource:-Device-Database#device_type

Is this what you are looking for?

**Comment by moranges** [comment]
Yes, that helps, thanks!

Just a quick thing. What devices would be represented for device type "Mobile Device"? Those are not supposed to be phones or tablets, so what would they be?

Thanks,

Mariano.

**Comment by paulrutter** [comment]
I'm not sure, but looking at the CSV source file i would guess that Mobile Device is either a phone or table, but based on the useragent it cannot be determined which one it is; hence just called "Mobile Device".

**Comment by moranges** [comment]
That works for me, thanks @paulrutter !
