### ISSUE TITLE
Is UserAgentParser thread safe?

### ISSUE THREAD

**Issue by FilipShark** [blueconic/browscap-java#20]
Hello, is `UserAgentParser` Thread safe, so could it be run concurrency?

**Comment by paulrutter** [comment]
Yes, it's thread safe, i'll update the documentation on it.
If you have any questions, please let me know.

**Comment by alamothe** [comment]
Should we create a single instance per (web) service? Thanks!

**Comment by paulrutter** [comment]
If possible i would reuse the same instance to prevent memory overhead.
