### ISSUE TITLE
literal indexes increasing when reload

### ISSUE THREAD

**Issue by michalkalisz** [blueconic/browscap-java#22]
Hi,

Thank you for your work!

I would like to reload UserAgentParser, but due to the fact that Literal.NUMBER_OF_INSTANCES is static it cause that SearchableString would allocate bigger array every time new UserAgentParser is instantied:
`
final int max = Literal.getNumberOfInstances() + 1;
myIndices = new int[max][];
`

Is it possible to make Literal.NUMBER_OF_INSTANCES not static? Maybe by moving it to  UserAgentFileParser as field ?

Thanks,
Michal

**Comment by arthurmeijer** [comment]
Hi Michal,

yes, that's possible. I'll try to fix this later this week.

Arthur

**Comment by paulrutter** [comment]
I'll push the latest release into the maven repo tomorrow. Thanks Arthur!

**Comment by paulrutter** [comment]
Published the 1.2.11 artifact to the maven repo. It might take up to a few hours before it will be visible.
Closing issue as this is fixed with https://github.com/blueconic/browscap-java/releases/tag/1.2.11.

**Comment by michalkalisz** [comment]
Thank you!
