### ISSUE TITLE
Browser Version full value like - 69.0.3497.100

### ISSUE THREAD

**Issue by vsprabhash** [blueconic/browscap-java#23]
Hi,

Can we get full browser version like _**69.0.3497.100.**_ Instead of getting major browser version value - 69.0

For example when we parse below agent, we will get **_65.0_** value as browser version. Can we get _full browser version value_?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Is there any work around to get full version? 

Thank you for sharing the information.

Thanks & Regards,
Prabhash V S

**Comment by paulrutter** [comment]
The full version is not part of the browscap source files, as can be seen here https://github.com/blueconic/browscap-java/blob/master/src/main/java/com/blueconic/browscap/BrowsCapField.java.

So, this library doesn't offer this information. Your best bet is to parse it out the the useragent with a regexp.

**Comment by tore-statsig** [comment]
Hey @paulrutter - as far as I can tell, I can load the parser with the following set of fields (I'm using this library in Kotlin, not java)

```
uaParser = UserAgentService().loadParser(
    listOf(
        BrowsCapField.BROWSER,
        BrowsCapField.BROWSER_VERSION,
        BrowsCapField.BROWSER_MINOR_VERSION,
        BrowsCapField.PLATFORM,
        BrowsCapField.PLATFORM_VERSION
    )
)
```

And yet when I parse the result, there is no Browser Version nor Minor Version field, only the Major Version:

![Screen Shot 2021-05-19 at 3 47 33 PM](https://user-images.githubusercontent.com/74584483/118894679-8da82680-b8b9-11eb-9981-7f5e1bc838b6.png)

Should they be listed as `BrowsCapField`s if they are not available as Capabilities?  Your previous response (from 2 years ago) seems to imply that if they were listed as fields, then this information would be available as a capability.  Perhaps this got missed in a subsequent update?

Thanks!

Tore

**Comment by paulrutter** [comment]
Hi @tore-statsig,

I'm not familiar with Kotlin, but the following java snippet yields the proper result:

```
        final UserAgentParser p = new UserAgentService()
                .loadParser(Arrays.asList(BrowsCapField.BROWSER, BrowsCapField.BROWSER_MINOR_VERSION));
        final Capabilities c = p.parse(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36");
        System.out.print(c.getValue(BrowsCapField.BROWSER));
        System.out.print(c.getValue(BrowsCapField.BROWSER_MINOR_VERSION));
``` 

Note the use of "getValue", which is needed when you request custom fields instead of the default ones.
It looks like Kotlin translates the getters to properties, so you might be able to use getValue in Kotlin as well?
