### ISSUE TITLE
Wrong browser version getting for the user agent 

### ISSUE THREAD

**Issue by vsprabhash** [blueconic/browscap-java#24]
For below useragent , I am getting wrong browser information. How can I get the correct one?

Mozilla/5.0 (X11; U; Linux Core i7-4980HQ; de; rv:32.0; compatible; JobboerseBot; http://www.jobboerse.com/bot.htm) Gecko/20100101 Firefox/38.0

Thanks for the help.

Thanks & Regards,
Prabhash V S

**Comment by paulrutter** [comment]
What info would you expect and what do you get from the library?

**Comment by paulrutter** [comment]
Closing due to no response. Re-open when you have more info.
