### ISSUE TITLE
UserAgentParser.parse not retrieving the platform version for Apple Device - iOS 12.4

### ISSUE THREAD

**Issue by benmak11** [blueconic/browscap-java#25]
Hi,

For this userAgent String:
`Mozilla/5.0 (iPhone; CPU iPhone OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1` 

I am unable to get the platform version of my iOS device from the Capabilities object that is returned after parsing... The platformVersion that is set is "Unknown". Seems to only affect iOS 12.4 but any release prior seems to work just fine.

Could we get more information about when this will be addressed?

**Comment by paulrutter** [comment]
We rely on browscap as our source of truth, so as long as www.browscap.org doesn't recognize it, we cannot as well. Please file an issue at browscap instead.
