### ISSUE TITLE
browscap version is out of date with main browscap.org site

### ISSUE THREAD

**Issue by jivedude** [blueconic/browscap-java#26]
Even though this site is saying we are up to date with version 6000034 of browscap this seems to be not the case.

browscap.org is reporting 6000034 to be released on September 24, 2019 and the last merge of the csv data was done here in July 8th.

I did a diff check between the two and there are a lot of differences.

Can we get an up to date release. I think we are missing for eg. Safari 13 and Firefox 69 detection capabilities.

**Comment by paulrutter** [comment]
That's strange, that would mean that there was a release without the version being increased. Will look into it.
For the time being, you can use your own zip file. See code example.

**Comment by paulrutter** [comment]
I've released a new version containing the latest 600035 files.
I'm will try and push it into the online maven repo soon, but i'm having some issues there.
For the time being, see releases.

**Comment by paulrutter** [comment]
It has been published to the maven repo now. Can take up to a few hours to sync though.

**Comment by jivedude** [comment]
Thanks so much for the quick turnaround!
