### ISSUE TITLE
wrong file extracted from provided zip

### ISSUE THREAD

**Issue by UglyBarnacle** [blueconic/browscap-java#27]
Hi,

I followed the instructions on providing an own browscap.zip file.
Our app queries via cron the version number from the browscap API to check if there is a newer version available. if so it downloads the zip file and stores it into gridfs of mongodb (or if no file at all). On init of the app, the database is queried for the latest file and then streamed to the UserAgentService as input. debugging showed, the first file inside the zip archive is not the csv, instead the php files and xml show up first, rendering the parser unusable always returning unknown values.

blindly assuming the first non-folder inside the zip seems to be a bad idea. 
using the zip from inside the package works seemlessy but is not what we opted for while the Code gives us the ability to provide an own file to stay up to date.

**Comment by paulrutter** [comment]
I understand the issue, i agree it would be better to only process .csv files inside the ZIP.
I have no time to fix it right now, but you're welcome to supply a PR!

**Comment by paulrutter** [comment]
Merged PR, issue can be closed. Thanks for the input.
