### ISSUE TITLE
Support for new Edge Chromium Browser

### ISSUE THREAD

**Issue by nitish1402** [blueconic/browscap-java#29]
Hi Team , Thanks for the awesome library.
As Microsoft has launched the new Edge chromium browser, so with its UA which is like this        
```
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.74 Safari/537.36 Edg/79.0.309.43
```
While the old Edge browser has UA 
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362
```
With the current version for browsecap-java we get browser as **Edge** . So do the team have anything in pipeline for differentiating both browsers, if no any tweaks in the API to achieve this rather than writing the wrapper.

Thanks

**Comment by paulrutter** [comment]
We follow browscap.org as our source of thruth. As long as they don't differentiate, we won't as well.
I would advice to file an issue in the browscap repository instead.

For now, as a workaround, you could use the "RENDERING_ENGINE_NAME" field to differentiate yourself. The new UA returns "Blink", while to old one returns "Edge".
