### ISSUE TITLE
Getting broader platform names

### ISSUE THREAD

**Issue by dinikolop** [blueconic/browscap-java#34]
Is there a way to programmatically fetch the most broad name of a platform with the library? Parser will return a specific name of a WIndows/iOS/Android etc version (e.g. "NT4_1" /"iOS_A_dynamic"/"Android_F_3_1"), but instead I would like to map these values to their broad platform name.
Thank you!

**Comment by paulrutter** [comment]
capabilities.getPlatform() isn't broad enough?

**Comment by dinikolop** [comment]
It actually is indeed. After having a more careful look at browscap's [resources](https://github.com/browscap/browscap/tree/6.0.x/resources), I understood that capabilities.getPlatform() will indeed return broad platform names such as Android, iOS, Linux etc. For Windows, it should return strings that start with `win`  (not in that casing always).
