### ISSUE TITLE
Library memory usage is very high

### ISSUE THREAD

**Issue by nmojir** [blueconic/browscap-java#37]
After creating the parser object with the following code, my application memory usage goes up to 1.7G from 150K. Is it usual?

`
UserAgentParser parser = new UserAgentService().loadParser(Arrays.asList(
			BrowsCapField.BROWSER, 
			BrowsCapField.BROWSER_MAJOR_VERSION,
			BrowsCapField.BROWSER_TYPE,
			BrowsCapField.DEVICE_TYPE, 
	                BrowsCapField.PLATFORM, 
	                BrowsCapField.PLATFORM_VERSION));
`

**Comment by paulrutter** [comment]
Loading the parser is very memory intensive initially, yes.
We advice to only load the parser once, and then re-use it for all subsequent lookups.
