### ISSUE TITLE
Android device model parser

### ISSUE THREAD

**Issue by jstakun** [blueconic/browscap-java#38]
Hello

I receive following user agent data from Android mobile devices:
Mozilla/5.0 (Linux; Android 11; **Pixel 2 XL**) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 6.0.1; **Nexus 5**) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Mobile Safari/537.36
I'd like to receive **bolded device model** info but it doesn't seem to be available in any fields. 

Please advise

**Comment by paulrutter** [comment]
That information is probably not available through browscap so this library cannot help with this. A regular expression might be an option though, if you know what to look for.
