### ISSUE TITLE
Wrong BROWSER_MAJOR_VERSION for Opera 77

### ISSUE THREAD

**Issue by heksoli** [blueconic/browscap-java#39]
Hello,

UA - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36 OPR/77.0.4054.277

Result - CapabilitiesImpl [myValues={BROWSER=Opera, BROWSER_TYPE=Default Browser, BROWSER_MAJOR_VERSION=0, PLATFORM=Unknown, PLATFORM_VERSION=Unknown, DEVICE_TYPE=Unknown}]

Can you update the config, please?
Thanks

**Comment by struk3lj** [comment]
I have the same issue. Following...

**Comment by paulrutter** [comment]
We follow http://browscap.org/ua-lookup as our source, and doesn't appear to be available there.
Please file an issue at the browscap source project on github, or even better a PR :)

**Comment by paulrutter** [comment]
Created issue here: https://github.com/browscap/browscap/issues/2522

**Comment by paulrutter** [comment]
Will be fixed in the upcoming release 6.0.47.
