### ISSUE TITLE
CSV File

### ISSUE THREAD

**Issue by baszero** [blueconic/browscap-java#4]
How does the CSV file get updated?
As I understand, it must be done individually (manually or per script).
Where can I get the latest CSV? Is it always the same location?
Thanks.

**Comment by paulrutter** [comment]
The csv file is manually updated by one of our contributors, which leads to a new release. The current version is the latest version, 6026. See browscap.org.

It's also possible to use your own csv file, see the readme on how to do that.

**Comment by paulrutter** [comment]
I'm closing this issue as i think your question is answeredm, isn't it? Please re-open if this is not the case.

**Comment by baszero** [comment]
Awesome, thanks.
