### ISSUE TITLE
Safari 14.1.x version is not parsed

### ISSUE THREAD

**Issue by oleg-lyalikov** [blueconic/browscap-java#40]
E.g. for user agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15" (got from here: https://www.whatismybrowser.com/guides/the-latest-user-agent/safari )
14.0 parsed ok

**Comment by paulrutter** [comment]
We use browscap.org as our source.
This library lies on top of those source files and doesn't do any additional things for parsing UA's.

Please file an issue with the browscap project instead.

For reference, check http://browscap.org/ua-lookup.
