### ISSUE TITLE
IOS 15 support

### ISSUE THREAD

**Issue by privetpoka** [blueconic/browscap-java#45]
Hello.
I am having issues with resolving os version of following UA:
Mozilla/5.0 (iPhone; CPU iPhone OS 15_0_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1
Will the new versions of IOS will be supported?

**Comment by paulrutter** [comment]
I already opened an issue for this in the browscap source project. To be continued.

**Comment by paulrutter** [comment]
See https://github.com/browscap/browscap/pull/2535

**Comment by paulrutter** [comment]
Fixed in 1.3.8 release.
