### ISSUE TITLE
Can't identify Edge browser in Linux and Mac

### ISSUE THREAD

**Issue by thiago-buarqque** [blueconic/browscap-java#48]
Since Edge now is chromium based it can be installed on Linux and Mac. But userAgentParser can't identify it when installed in some version of others OS.

For example, does not work with:
- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44

But it works with:
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44

Couldn't identify a version of Linux that works.

**Comment by paulrutter** [comment]
@thiago-buarqque does this work on http://browscap.org/ua-lookup? If not, you should file an issue with https://github.com/browscap/browscap instead.

**Comment by thiago-buarqque** [comment]
It doesn't. I'll open an issue on browscap. Thanks
