### ISSUE TITLE
use "IS_LITE_ONLY" to speed up parsing

### ISSUE THREAD

**Issue by frazjp65** [blueconic/browscap-java#5]
Add an option to use only "lite" user agent rules. It will be less accurate, but much faster.

**Comment by paulrutter** [comment]
Thanks for your pr! 

Can you explain why one would like to use these less accurate values? Parsing all rules is very fast, and when you implement a cache on top of it, i don't see why we need this?
Please elaborate so we can determine what to do with this.

**Comment by frazjp65** [comment]
I currently use [UserAgentUtils](http://www.bitwalker.eu/software/user-agent-utils), but it is EOL and out of date. It recommended that I use BrowsCap. When I benchmarked the three BrowsCap libraries on their site, this was the fastest library. Unfortunately, the library is still two orders of magnitude slower than the existing library. The PR brings it within one order of magnitude of the current version. When I add a cache, I hope it brings it up to par with the existing library. I can afford a loss of accuracy because the library I am replacing is somewhat older and probably not accurate anyway.

**Comment by paulrutter** [comment]
@arthurmeijer what do you think?

**Comment by frazjp65** [comment]
I compared this library, BrowsCap4J, UserAgentUtils, and Yauaa. This library much slower than UserAgentUtils.

**Comment by paulrutter** [comment]
Right, i'll discuss with my collegue.
Bear in mind that UserAgentUtils is not nearly as accurate as this library, so the comparison is not entirely fair :)

**Comment by frazjp65** [comment]
Did your colleague ever get back to you about this?

**Comment by paulrutter** [comment]
Yes, we are looking into this, but we're not sure if this is something we are going to add, because:
- one can use a custom CSV file which only contains the "lite" rules. That would have the same effect as this PR.
- https://github.com/browscap/browscap/wiki/Resource%3A-User-Agents-Database shows that "LiteMode" is a deprecated property. That would indicate that it's no longer up to date, making the library less and less accurate.

**Comment by paulrutter** [comment]
@frazjp65 what do you think about the issues we raised?

**Comment by frazjp65** [comment]
I agree with your findings. I will look for a different approach to my problem. Thanks!
