### ISSUE TITLE
Jupyter notebook integration

### ISSUE THREAD

**Issue by prk2331** [blueconic/browscap-java#53]
Hi @paulrutter 
Hope you are dong well, paulrutter can you please guide me **how we can integrate workbench in our data science project**, I have a Toolkit in which I have a data science section, for my University Project.
my agenda is :-
1. Listing of Notebooks
2. Creating of Notebooks
3. Update Notebooks
4. Schedule Notebooks
    Actually i google lots of stuff, but unable to find any perfect solution for this. Can you please guide 
    I tried to host my jupyter and call through iframe, would restrict me for the customizations.
    
    Best Regards
    Prince (Future Tech Stack Learner)

**Comment by paulrutter** [comment]
Seems like this question is out of place and has nothing to do with this project.
