### ISSUE TITLE
Windows 11 labeled as Windows 10

### ISSUE THREAD

**Issue by jesusrodriguezmjp** [blueconic/browscap-java#54]
I have been doing some test with the last version, and it doesn´t detect Windows 11 (I think all the test have been made from Chrome).

Is there a workaround? I know the user agent it´s not always trustable, but its a good hint.

Thanks!

**Comment by paulrutter** [comment]
That would be a request for the browscap source files repository: https://github.com/browscap/browscap
This library is just a java library on top of those source files.
