### ISSUE TITLE
Change in GPG Keys 

### ISSUE THREAD

**Issue by DennisRippinger** [blueconic/browscap-java#60]
Hello together,

Out of curiosity, I run the `pgpverify` in our builds. I observed a change in the used key from [0xAF4A53C44A049A1A1E6081F6BEF51C4F24808A88](https://keyserver.ubuntu.com/pks/lookup?search=0xAF4A53C44A049A1A1E6081F6BEF51C4F24808A88&fingerprint=on&op=index) from @paulrutter to this key [0x2AE86C271AF99EE909A87471060AD4631021B2DC](https://keys.openpgp.org/search?q=0x2AE86C271AF99EE909A87471060AD4631021B2DC), which provides no metadata at all.

Do you know if this is meant?

**Comment by paulrutter** [comment]
Yes, i indeed generated a new key since i got a new laptop. Not sure why the new one contains no metadata, it might be in a newer format though.
