### ISSUE TITLE
browscap-java has high latency and is slow to obtain information.

### ISSUE THREAD

**Issue by wangrunze2023** [blueconic/browscap-java#64]
Use this jar package to obtain user browser information and operation information. Each call takes 5 minutes, and the delay is very high. 🙁

**Comment by paulrutter** [comment]
You should re-use the parser instance instead of creating one per lookup.
Does that solve your issue?

**Comment by wangrunze2023** [comment]
> You should re-use the parser instance instead of creating one per lookup. Does that solve your issue?
> 
> ```
> private static final new UserAgentParser;
> 
> constructor() {
>   myParser = new UserAgentService().loadParser(); // handle IOException and ParseException
> } 
> 
> // initialize parser once and re-use instance on every lookup 
> myParser.parse(userAgent)
> ```


It's ready, thank you very much！ 😄

**Comment by paulrutter** [comment]
Nice!
