### ISSUE TITLE
Windows 11 not detected instead Win 10 is gotten 

### ISSUE THREAD

**Issue by Tirador1** [blueconic/browscap-java#65]
I have windows 11 and appears as 10.
[This isn't a bug. It's by design for compatibility issues](https://answers.microsoft.com/en-us/windows/forum/all/why-does-windows-11-show-windows-10-as-os-version/2da93b57-951b-4771-a328-36ab5ff685d7).
We can just return Win10/11 on `BrowsCapField.PLATFORM`

**Comment by paulrutter** [comment]
This would be something that needs to be fixed in the browscap source files instead.
Can you file an issue with https://github.com/browscap/browscap/ instead?
