### ISSUE TITLE
IE9 detection fails when in emulation mode

### ISSUE THREAD

**Issue by nyon** [blueconic/browscap-java#8]
When using this library to detect for different Internet Explorer version, it fails for an emulated Internet explorer 9. A *real* Internet Explorer 9 would send the following user agent:

    Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)

while an emulated one sends the following

    Mozilla/5.0(compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)

Note the missing space between `Mozilla/5.0` and `(compatible; ...`.

I worked around it by replacing `Mozilla/5.0(compatible` with `Mozilla/5.0 (compatible`, but perhaps this could be fixed in a better way in your library (if you want to fix it at all).

**Comment by paulrutter** [comment]
Hi @nyon,

This library follows the BrowsCap.org source files; we do not post-process any of the data.
See http://browscap.org/ua-lookup; the output of that page is what this library will return as well.

If you want this fixed, please report it to the BrowsCap github https://github.com/browscap/browscap/issues.

Thanks!
